/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TdspKliDh3f
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button, ButtonProps } from "@/components/ui/button"
import { cn } from "@nextui-org/theme";

export function CornerButton({children, className, onClick, ...props} : ButtonProps) {
  return (
      <Button className={cn("bg-transparent text-primary px-2 py-2 relative group hover:bg-transparent font-saturday text-[24px] font-bold mr-1 ml-1 mt-2 mb-2", className)} onClick={onClick} {...props}>
		  <div className="absolute top-0 left-0 w-[30px] h-[20px] border-t-4 border-l-4 border-[#000000] rounded-none group-hover:block group-hover:border-primary group-hover:opacity-100 opacity-0 transition-all duration-300" />
		  <div className="absolute bottom-0 right-0 w-[30px] h-[20px] border-b-4 border-r-4 border-[#000000] rounded-none group-hover:block group-hover:border-primary group-hover:opacity-100 opacity-0 transition-all duration-300" />
		  {children}
      </Button>
  );
}

export function TitleButton({children, className, ...props} : ButtonProps) {
  return (
      <Button className="bg-transparent text-black px-4 py-8 relative group hover:bg-transparent font-saturday text-[40px] font-bold mr-1 ml-1 mt-4 mb-4 disabled:opacity-100" disabled {...props}>
		  <div className="absolute top-0 left-0 w-[40px] h-[30px] border-t-5 border-l-5 border-[#000000] rounded-none group-hover:block group-hover:border-black" />
		  <div className="absolute bottom-0 right-0 w-[40px] h-[30px] border-b-5 border-r-5 border-[#000000] rounded-none" />
		  {children}
      </Button>
  );
}
